# Generated by Django 2.2.7 on 2019-11-21 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order_orderedproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproducts',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.Order'),
        ),
    ]
