# Generated by Django 2.2.7 on 2019-11-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191121_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='OrderedProducts',
        ),
    ]
